In [1]:
import pandas as pd
import numpy as np
#Task 1
np.random.seed(42)
data = {
'video_id': [f'V{i:03d}' for i in range(1, 21)],
'views_start': np.random.randint(1000, 10000, 20),
'views_end': np.random.randint(3000, 50000, 20),
'category': np.random.choice(['Юмор', 'IT', 'Еда'], 20)
}
df = pd.DataFrame(data)
df.to_csv('tiktok_videos.csv', index=False)

print(df.head())

  video_id  views_start  views_end category
0     V001         8270      31693       IT
1     V002         1860       9396     Юмор
2     V003         6390      30480       IT
3     V004         6191      44434       IT
4     V005         6734      28658       IT


In [5]:
# 1. Рассчитать growth_rate — процент роста просмотров за день
df['growth_rate'] = ((df['views_end'] - df['views_start']) / df['views_start']) * 100

# 2. Отфильтровать видео с ростом более 200%
hype_df = df[df['growth_rate'] > 200]
hype_df.head()

,video_id,views_start,views_end,category,growth_rate
0,V001,8270,31693,IT,283.228537
1,V002,1860,9396,Юмор,405.161290
2,V003,6390,30480,IT,376.995305
3,V004,6191,44434,IT,617.719270
4,V005,6734,28658,IT,325.571726


In [6]:
# 3. Подсчитать количество хайповых видео по категориям
hype_counts = hype_df['category'].value_counts().reset_index()
hype_counts.columns = ['Категория', 'Количество']

# 4. Вывести ТОП-3 самых быстрорастущих видео
top_3 = df.nlargest(3, 'growth_rate')

print("--- Хайповых видео по категориям ---")
print(hype_counts.to_string(index=False))
print("\n--- ТОП-3 самых быстрорастущих видео ---")
print(top_3[['video_id', 'category', 'growth_rate']].to_string(index=False))

--- Хайповых видео по категориям ---
Категория  Количество
       IT           8
     Юмор           2
      Еда           2

--- ТОП-3 самых быстрорастущих видео ---
video_id category  growth_rate
    V018       IT  1942.399267
    V007       IT  1361.869031
    V011      Еда  1344.059590


In [7]:
#Task 2

road = np.zeros((20, 20), dtype=int)
road[:, 10] = 1
road = np.roll(road, -2, axis=1)
road[::2, 8] = 0

print(road)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]


In [8]:
#Task 3

messages = [
    "Привет всем участникам чата",
    "Розыгрыш iPhone прямо сейчас!!!",
    "Кто знает хороший курс по Python?",
    "@admin помогите разобраться",
    "КРИПТА только растет #bitcoin $$$",
    "Отличная статья про машинное обучение",
    "Розыгрыш* призов каждый день",
    "Подскажите книгу для начинающих",
    "Заработок на крипте легко",
    "Спасибо за помощь",
    "### Супер предложение ###",
    "Изучаю pandas для анализа данных",
    "Розыгрыш 1000$ для всех",
    "Какой фреймворк выбрать для веба?",
    "Крипта это будущее финансов",
]
df_chat = pd.DataFrame({'message': messages})


In [9]:
df_chat['is_spam'] = df_chat['message'].str.contains(r'крипт|розыгрыш', case=False, na=False)
df_chat['message_clean'] = df_chat['message'].str.replace(r'[@#$*]', '', regex=True)
df_chat['word_count'] = df_chat['message_clean'].str.split().str.len()
df_filtered = df_chat[(df_chat['word_count'] > 3) & (~df_chat['is_spam'])]
df_filtered[['message_clean', 'word_count']]


,message_clean,word_count
0,Привет всем участникам чата,4
2,Кто знает хороший курс по Python?,6
5,Отличная статья про машинное обучение,5
7,Подскажите книгу для начинающих,4
11,Изучаю pandas для анализа данных,5
13,Какой фреймворк выбрать для веба?,5


In [10]:
#Task 4
gan_tensor = np.random.normal(loc=0.0, scale=1.0, size=(10, 64, 64, 3))
random_idx = np.random.randint(0, 10)
gan_tensor[random_idx, ::4, :] = [255, 0, 0]
mean_image = np.mean(gan_tensor, axis=0)

print("Форма исходного тензора:", gan_tensor.shape)
print("Индекс случайно выбранного изображения:", random_idx)
print("Форма усредненного изображения:", mean_image.shape)


Форма исходного тензора: (10, 64, 64, 3)
Индекс случайно выбранного изображения: 0
Форма усредненного изображения: (64, 64, 3)


In [11]:
#Task 5
np.random.seed(42)
users = [f'User_{i}' for i in range(1, 11)]
genres = ['Рок', 'Поп', 'Техно', 'Рэп']
data = np.random.randint(0, 100, size=(10, 4))
df_music = pd.DataFrame(data, columns=genres, index=users)

In [12]:
music_matrix = df_music.to_numpy()
row_sums = music_matrix.sum(axis=1, keepdims=True)
norm_matrix = music_matrix / row_sums
user_1_profile = norm_matrix[0]
distances = np.sqrt(np.sum((norm_matrix - user_1_profile)**2, axis=1))
distances[0] = np.inf
closest_idx = np.argmin(distances)
best_match = df_music.index[closest_idx]

print(f"Наиболее похожий пользователь: {best_match} (расстояние: {distances[closest_idx]:.4f})")
print("\nСравнение профилей (нормированных):")
print(f"User_1:   {norm_matrix[0]}")
print(f"{best_match}:   {norm_matrix[closest_idx]}")


Наиболее похожий пользователь: User_9 (расстояние: 0.1861)

Сравнение профилей (нормированных):
User_1:   [0.22368421 0.40350877 0.06140351 0.31140351]
User_9:   [0.15185185 0.33703704 0.21851852 0.29259259]
